- name: secret variables demo
  hosts: localhost
  connection: local
  vars_prompt:
    - name: username
      prompt: "please enter username"
      private: False
    - name: password
      promt: "Please enter password"
      private: True
  tasks:
  - name: printing
    debug:
      msg: "Username is {{ username }} and passowrd is {{ password }}"