- name: local variables in inventory demo
  hosts: frontend
  #connection: local
  tasks:
  - name: printing
    debug:
      msg: "Hi I am learning {{ Course }} , Trainer is {{ Trainer }} and Duration is {{ Duration }}"