[frontend]
;specify all the target servers 
;COURSE="Ansible for NODE-1" # These are called as individual host vars
172.31.34.252


[catalogue]
172.31.34.249

[cart]
172.31.34.261

[payment]
172.31.34.272


;groups of groups in yaml file near hosts you can mention roboshop then it will fetch all servers
[roboshop:children]
frontend
catalogue
cart
payment